---
title: "Coronavirus"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(coronavirus)
data(coronavirus)

`%>%` <- magrittr::`%>%`


df <- coronavirus %>% 
  # dplyr::filter(date == max(date)) %>%
  dplyr::group_by(Country.Region, type) %>%
  dplyr::summarise(total = sum(cases)) %>%
  tidyr::pivot_wider(names_from =  type, 
                     values_from = total) %>%
  dplyr::arrange(-confirmed) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(country = dplyr::if_else(Country.Region == "United Arab Emirates", "UAE", Country.Region)) %>%
  dplyr::mutate(country = dplyr::if_else(country == "Mainland China", "China", country)) %>%
  dplyr::mutate(country = dplyr::if_else(country == "North Macedonia", "N.Macedonia", country)) %>%
  dplyr::mutate(country = trimws(country)) %>%
  dplyr::mutate(country = factor(country, levels = country))

df_daily <- coronavirus::coronavirus %>% 
  dplyr::group_by(date, type) %>%
  dplyr::summarise(total = sum(cases, na.rm = TRUE)) %>%
  tidyr::pivot_wider(names_from = type,
                     values_from = total) %>%
  dplyr::arrange(date) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(confirmed_cum = cumsum(confirmed),
                death_cum = cumsum(death),
                recovered_cum = cumsum(recovered))

df1 <- coronavirus %>% dplyr::filter(date == max(date))

```

Summary
=======================================================================
Row
-----------------------------------------------------------------------

### confirmed {.value-box}

```{r}

valueBox(value = paste(sum(df$confirmed)), caption = "Confirmed Cases", icon = "fas fa-ambulance", color = "#1f77b4")
```

### recovered {.value-box}

```{r}
valueBox(value = paste(sum(df$recovered, na.rm = TRUE), " cases (",
                       round(100 * sum(df$recovered, na.rm = TRUE) / sum(df$confirmed), 1), 
                       "%)", sep = ""), 
         caption = "Recovered Cases", icon = "fas fa-heartbeat", 
         color = "green")
```

### death {.value-box}

```{r}

valueBox(value = paste(sum(df$death, na.rm = TRUE), " cases (",
                       round(100 * sum(df$death, na.rm = TRUE) / sum(df$confirmed), 1), 
                       "%)", sep = ""),
         caption = "Death Cases", 
         icon = "fas fa-heart-broken", 
         color = "red")
```


Row
-----------------------------------------------------------------------

### Total Cases by Type/Country

```{r daily_summary}


plotly::plot_ly(data = df, 
                x = ~ country, 
                y = ~ confirmed, 
                # text =  ~ confirmed, 
                # textposition = 'auto',
                type = "bar", 
                name = "Confirmed") %>%
  plotly::add_trace(y = ~ recovered, 
                    # text =  ~ recovered, 
                    # textposition = 'auto',
                    name = "Recovered",
                    marker = list(color = "green")) %>%
  plotly::add_trace(y = ~ death, 
                    # text =  ~ death, 
                    # textposition = 'auto',
                    name = "Death",
                    marker = list(color = "red")) %>%
  plotly::layout(barmode = 'stack',
                 yaxis = list(title = "Total Cases (log scaled)",
                              type = "log"),
                 xaxis = list(title = ""),
                 hovermode = "compare",
                  margin =  list(
                   # l = 60,
                   # r = 40,
                   b = 10,
                   t = 10,
                   pad = 2
                 ))


  


```

Row {data-width=400}
-----------------------------------------------------------------------


### Daily Cumulative Cases by Type
    
```{r}

plotly::plot_ly(data = df_daily) %>%
  plotly::add_trace(x = ~ date, 
                    y = ~ confirmed_cum, 
                    type = "scatter", 
                    mode = "lines+markers",
                    name = "Confirmed",
                    line = list(color = "#1f77b4")) %>%
  plotly::add_trace(x = ~ date, 
                    y = ~ recovered_cum, 
                    type = "scatter", 
                    mode = "lines+markers",
                    name = "Recovered",
                    line = list(color = "green"),
                    marker = list(color = "green")) %>%
  plotly::add_trace(x = ~ date, 
                    y = ~ death_cum, 
                    type = "scatter", 
                    mode = 'lines+markers',
                    name = "Death",
                    line = list(color = "red"),
                    marker = list(color = "red")) %>%
  plotly::layout(title = "",
                 yaxis = list(title = "Cumulative Number of Cases"),
                 xaxis = list(title = "Date"),
                 legend = list(x = 0.1, y = 0.9),
                 hovermode = "compare")
  

```


### Recovery and Death Rates by Country
    
```{r}
df_summary <- coronavirus::coronavirus %>% 
  # dplyr::filter(Country.Region != "Others") %>%
  dplyr::group_by(Country.Region, type) %>%
  dplyr::summarise(total_cases = sum(cases)) %>%
  tidyr::pivot_wider(names_from = type, values_from = total_cases) %>%
  dplyr::arrange(- confirmed) %>%
  dplyr::filter(confirmed >= 25) %>%
  dplyr::mutate(recover_rate = recovered / confirmed,
         death_rate = death / confirmed)  
df_summary %>%
  DT::datatable(rownames = FALSE,
            colnames = c("Country", "Confirmed", "Recovered", "Death", "Recovery Rate", "Death Rate"),
            options = list(pageLength = nrow(df_summary), dom = 'tip')) %>%
  DT::formatPercentage("recover_rate", 2) %>%
  DT::formatPercentage("death_rate", 2) 
```


Trends
=======================================================================


Column {data-width=400}
-------------------------------------
    
### Distribution of New Cases 
    
```{r}
max_date <- max(coronavirus$date)
coronavirus %>% 
  dplyr::filter(type == "confirmed", date == max_date) %>%
  dplyr::group_by(Country.Region) %>%
  dplyr::summarise(total_cases = sum(cases)) %>%
  dplyr::arrange(-total_cases) %>%
  dplyr::mutate(country = factor(Country.Region, levels = Country.Region)) %>%
  dplyr::ungroup() %>%
  plotly::plot_ly(labels = ~ country, 
          values = ~ total_cases,
          type = "pie",
          textposition = 'inside',
        textinfo = 'label+percent',
        insidetextfont = list(color = '#FFFFFF'),
        hoverinfo = 'text',
        text = ~ paste(country, "<br />",
                     "Number of confirmed cases: ", total_cases, sep = "")) %>%
  # plotly::add_pie(hole = 0.6) %>%
  plotly::layout(title = "",
                 margin =  list(
                   l = 10,
                   r = 10,
                   b = 10,
                   t = 10,
                   pad = 2
                 )) %>%
  plotly::add_annotations(text = paste("During", max_date, sep = " "),
                          xref = "paper",
                          yref = "paper",
                          showarrow = FALSE,
                          x = 0,
                          y = 1) %>%
  plotly::hide_legend()
```


### Daily Distribution of Confirmed Cases - China vs. Rest of the World
    
```{r}
daily_confirmed <- coronavirus %>%
  dplyr::filter(type == "confirmed") %>%
  dplyr::mutate(country = dplyr::if_else(Country.Region == "Mainland China", 
                                         "China", 
                                         "Rest of the World")) %>%
  dplyr::group_by(date, country) %>%
  dplyr::summarise(total = sum(cases)) %>% 
  dplyr::ungroup() %>%
  tidyr::pivot_wider(names_from = country, values_from = total) 

#----------------------------------------
# Plotting the data

daily_confirmed %>%
  plotly::plot_ly(x = ~date, 
                  y = ~ China, 
                  name = 'China', 
                  type = 'scatter', 
                  mode = 'none', 
                  stackgroup = 'one', 
                  groupnorm = 'percent', 
                  fillcolor = "#d62728") %>% 
  plotly::add_trace(y = ~ `Rest of the World`, name = 'Rest of the World', fillcolor = "#9467bd") %>%
  plotly::layout(title = "",
                 yaxis = list(title = "Proportion of New Cases", ticksuffix = '%'),
                 xaxis = list(title = "Date"),
                 legend = list(orientation = 'h'),
                 # paper_bgcolor = "black",
                 # plot_bgcolor = "black",
                 # font = list(color = 'white'),
                 hovermode = "compare",
                 margin =  list(
                   # l = 60,
                   # r = 40,
                   b = 10,
                   t = 10,
                   pad = 2
                 ))

```
   
Column {data-width=600}
-------------------------------------
   
### Chart 3

```{r}

  
```   
 
### New Cases
    
```{r}
coronavirus %>% 
  dplyr::filter(date == max(date)) %>%
  dplyr::group_by(Country.Region, type) %>%
  dplyr::summarise(total = sum(cases)) %>%
  tidyr::pivot_wider(names_from = type, values_from = total) %>%
  dplyr::arrange(-confirmed) %>%
  DT::datatable(caption =paste("During", max_date, sep = " "),
    rownames = FALSE,
            colnames = c("Country", "Confirmed", "Recovered", "Death"),
            options = list(pageLength = 10, dom = 'tip'))
```

Data
=======================================================================

```{r}
coronavirus %>% 
  dplyr::select(Date = date, Province = Province.State, Country = Country.Region, `Case Type` = type, `Number of Cases` = cases) %>%
  DT::datatable(rownames = FALSE,
            options = list(searchHighlight = TRUE, 
                           pageLength = 20), filter = 'top')
```



About
=======================================================================

