version: "3.9"
services:
  rstudio-server:
    image: rkrispin/coronavirus_dashboard_rstudio:dev
    ports:
      - "8787:8787"
    volumes:
      - type: "bind"
        source: "$COVID_DASH_DIR"
        target: "/home/rstudio"
      - type: "bind"
        source: "$RSTUDIO_CONFIG"
        target: "/home/rstudio/.config/rstudio"

